services:
  api-server:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - NODE_ENV=development # change this
      - PORT=5000
      - DB_NAME=sqlite.db
      - JWT_SECRET=<set-your-jwt_secret> # change this
      - UPLOAD_PATH=/app/uploads
    volumes:
      - ./backend/database:/app/database
    networks:
      - kulmsin-network
    depends_on:
      fe-build:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5000/api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  api-doc-server:
    image: docker.swagger.io/swaggerapi/swagger-ui:v5.30.2
    restart: unless-stopped
    networks:
      - kulmsin-network
    volumes:
      - ./backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      - TZ=Asia/Jakarta
      - API_URL=openapi.yaml
    depends_on:
      api-server:
        condition: service_healthy

  fe-build:
    image: oven/bun:1
    working_dir: /app
    restart: no
    volumes:
      - ./frontend:/app
      - ./fe-dist:/app/dist
    networks:
      - kulmsin-network
    command:
      [
        "sh",
        "-lc",
        "bun install --frozen-lockfile && bun run build && rm -rf node_modules",
      ]

  nginx:
    image: nginx:1-alpine
    ports:
      - 8080:80
    depends_on:
      fe-build:
        condition: service_completed_successfully
      api-server:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./fe-dist:/etc/nginx/html
    networks:
      - kulmsin-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
        reservations:
          cpus: "0.1"
          memory: 16M

networks:
  kulmsin-network:
    driver: bridge
