services:
  api-server:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - PORT=5000
      - DB_NAME=sqlite.db
      - JWT_SECRET=<set-your-jwt_secret>
    volumes:
      - ./backend/database:/app/database
    networks:
      - kulmsin-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  fe-build:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./fe-dist:/app/dist

  nginx:
    image: nginx:1-alpine
    ports:
      - 8080:80
    depends_on:
      - fe-build
      - api-server
    restart: unless-stopped
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./fe-dist:/etc/nginx/html
    networks:
      - kulmsin-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
        reservations:
          cpus: "0.1"
          memory: 16M

networks:
  kulmsin-network:
    driver: bridge
